platform: linux
image_resource:
  type: docker-image
  source:
    repository: govuk/ecs-cli
    tag: latest # TODO - manage image versions ourselves instead of using latest
    username: ((docker_hub_username))
    password: ((docker_hub_authtoken))
params:
  AWS_REGION: eu-west-1
  ASSUME_ROLE_ARN: 'arn:aws:iam::430354129336:role/govuk-concourse-deployer'
  ECS_SERVICE:
  WORKSPACE:
run:
  path: ./src/concourse/tasks/await-deploy-complete.sh
