platform: linux
image_resource:
  type: registry-image
  source:
    repository: vito/oci-build-task
inputs:
- name: git-repo
outputs:
- name: image
params:
  CONTEXT: git-repo
  DOCKERFILE: git-repo/Dockerfile
run:
  path: build
