platform: linux
image_resource:
  type: docker-image
  source:
    repository: govuk/ecs-cli
    tag: latest # TODO - manage image versions ourselves instead of using latest
    username: ((docker_hub_username))
    password: ((docker_hub_authtoken))
inputs:
  - name: govuk-infrastructure
    path: src
  - name: task-definition-arn
params:
  AWS_REGION: eu-west-1
  ASSUME_ROLE_ARN:
  ECS_SERVICE:
  WORKSPACE:
run:
  path: ./src/concourse/tasks/update-ecs-service.sh
