apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: GOVUK_APP_DOMAIN
              value: "{{ .Values.appGovukAppDomain | default (printf "%s.%s.%s" .Release.Namespace .Values.govukEnvironment .Values.clusterDomain) }}"
            - name: GOVUK_APP_DOMAIN_EXTERNAL
              value: "{{ .Values.appGovukDomainExternal | default (printf "%s.%s.%s" .Release.Namespace .Values.govukEnvironment .Values.govukDomainExternal) }}"
            - name: GOVUK_APP_NAME
              value: "{{ .Values.appGovukAppName | default .Release.Name }}"
            - name: GOVUK_WEBSITE_ROOT
              value: "{{ .Values.appGovukWebsiteRoot | default (printf "https://www-origin.%s.%s.%s" .Release.Namespace .Values.govukEnvironment .Values.govukDomainExternal) }}"
            - name: DEFAULT_TTL
              value: "{{ .Values.appDefaultTtl }}"
            - name: GOVUK_ASSET_ROOT
              value: "{{ .Values.appGovukAssetRoot | default (printf "https://assets.%s.%s.%s" .Release.Namespace .Values.govukEnvironment .Values.govukDomainExternal) }}"
            - name: GOVUK_ENVIRONMENT
              value: "{{ .Values.govukEnvironment }}"
            - name: PORT
              value: "{{ .Values.containerPort }}"
            - name: RAILS_ENV
              value: "{{ .Values.govukEnvironment }}"
            - name: REDIS_URL
              value: "{{ .Values.appRedisUrl | default (printf "redis://redis.ecs.%s.%s:6379" .Values.govukEnvironment .Values.govukDomainExternal) }}" #TODO: use EKS Redis cluster
            - name: GOVUK_APP_ROOT
              value: "{{ .Values.appGovukAppRoot }}"
            - name: GOVUK_APP_TYPE
              value: "{{ .Values.appGovukAppType }}"
            - name: SECRET_KEY_BASE
              value: "secret" #TODO: fix when we know how to handle secrets
          {{- with .Values.appExtraEnv }}
            {{- . | toYaml | trim | nindent 12 }}
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          livenessProbe:
            httpGet:
              path: /healthcheck/live
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthcheck/ready
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 30
            periodSeconds: 5
