name: Build and publish github-cli image to ECR

on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - "docker/images/github-cli/Dockerfile"

jobs:
  build-publish-image-to-ecr:
    uses: alphagov/govuk-infrastructure/.github/workflows/ci-ecr.yaml@main
    with:
      ecr_repository_name: github-cli
      additional_build_args: "-f docker/images/github-cli/Dockerfile"
    secrets:
      AWS_GOVUK_ECR_ACCESS_KEY_ID: ${{ secrets.AWS_GOVUK_ECR_ACCESS_KEY_ID }}
      AWS_GOVUK_ECR_SECRET_ACCESS_KEY: ${{ secrets.AWS_GOVUK_ECR_SECRET_ACCESS_KEY }}
