name: Validate Github Repos YAML
on:
  push:
    paths: ['.github/workflows/**', 'terraform/deployments/github/**']
jobs:
  github_repos_validation:
    name: Validate Github Repos YAML
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          show-progress: false

      - name: Validate YAML Schema
        run: |
          yq -o=json '. ' terraform/deployments/github/repos.yml > repos.json
          npx ajv-cli validate -s terraform/deployments/github/schemas/repos.schema.json -d repos.json
